version: "3.8"

services:
  frontend:
    container_name: todolist-frontend-app
    image: todolist-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
